name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync --dev --frozen

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Run Ruff
        run: uv run ruff check .

      - name: Run Pyright
        run: uv run pyright

      - name: Run tests
        run: uv run pytest
